version: '3.8'

services:
  web:
    container_name: infoDock-v2.0
    build: .
    working_dir: /src
    volumes:
      - .:/src
    ports:
     - "4204:4204"
    environment:
       - SECRET_KEY=${SECRET_KEY}
       - DATABASE_URL_POSTGRES=${DATABASE_URL_POSTGRES}
       - DATABASE_URL_SQLITE=${DATABASE_URL_SQLITE}
       - SQLALCHEMY_TRACK_MODIFICATIONS=${SQLALCHEMY_TRACK_MODIFICATIONS}
       - SQLALCHEMY_ECHO=${SQLALCHEMY_ECHO}
       - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
       - UPLOAD_FOLDER=${UPLOAD_FOLDER}
    env_file:
      - .env
    tty: true
    restart: always
    command: "flask run --host='0.0.0.0' --port=4204 --debug"
